# Generated by Django 2.2.5 on 2019-09-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='players',
            field=models.ManyToManyField(to='commands.Player'),
        ),
    ]
